import { AlertTriangle, ArrowRight, Coffee, Loader2, ShieldCheck, Sparkles } from "lucide-react";
import { startLogin } from "@/const";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { formatPkr } from "@/contexts/CafeContext";
import { ProductMediaManager } from "@/components/ProductMediaManager";

const statusMeta = { new: { label: "New", next: "confirmed" }, confirmed: { label: "Confirmed", next: "preparing" }, preparing: { label: "Preparing", next: "ready" }, ready: { label: "Ready", next: "out_for_delivery" }, out_for_delivery: { label: "Out for delivery", next: "completed" }, completed: { label: "Completed", next: null }, cancelled: { label: "Cancelled", next: null } } as const;

export default function AdminOrdersPage() { const { user, loading } = useAuth(); if (loading) return <div className="cafe-shell grid min-h-screen place-items-center"><Loader2 className="animate-spin text-[#e4b878]" /></div>; if (!user) return <Restricted title="Owner sign-in required" detail="Sign in with the Coffeemistry owner account to manage WhatsApp orders." action="Sign in securely" onClick={startLogin} />; if (user.role !== "admin") return <Restricted title="Owner access only" detail="This workspace is restricted to the Coffeemistry owner." action="Return to Coffeemistry" onClick={() => (window.location.href = "/")} />; return <DashboardLayout><OwnerWorkspace /></DashboardLayout>; }
function OwnerWorkspace() { const utils = trpc.useUtils(); const ordersQuery = trpc.admin.orders.useQuery(); const advance = trpc.admin.advanceOrder.useMutation({ onSuccess: () => utils.admin.orders.invalidate() }); const orders = ordersQuery.data ?? []; const active = orders.filter(order => !["completed", "cancelled"].includes(order.status)); return <div className="mx-auto max-w-6xl space-y-7 pb-10"><section className="glass-panel relative overflow-hidden rounded-[2rem] p-7 text-[#fffaf0] sm:p-10"><div aria-hidden="true" className="absolute right-0 top-0 h-52 w-52 rounded-full bg-[#e2a864]/12 blur-[75px]" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-[.62rem] font-bold uppercase tracking-[.18em] text-[#e4b878]"><ShieldCheck size={15} /> Owner workspace</p><h1 className="mt-5 font-display text-6xl leading-[.78]">Orders</h1><p className="mt-5 max-w-xl text-sm leading-7 text-[#d1b9a1]">WhatsApp order requests are recorded here before the conversation begins. Manage fulfilment from New through Completed.</p></div><a href="/" className="cinematic-button inline-flex h-10 items-center gap-2 rounded-full border border-white/15 bg-white/[.04] px-4 text-xs font-bold uppercase tracking-[.12em] text-[#f5eee4] hover:bg-white/8">View site <ArrowRight size={15} /></a></div></section><section className="grid gap-4 sm:grid-cols-3"><Metric label="New orders" value={orders.filter(order => order.status === "new").length} /><Metric label="In progress" value={orders.filter(order => ["confirmed", "preparing", "ready", "out_for_delivery"].includes(order.status)).length} dark /><Metric label="Active orders" value={active.length} green /></section><section className="glass-panel overflow-hidden rounded-[2rem]"><div className="border-b border-white/10 px-6 py-6"><div className="flex items-center gap-2 text-[.62rem] font-bold uppercase tracking-[.18em] text-[#d5a66a]"><Sparkles size={13} /> Live order queue</div><h2 className="mt-4 font-display text-4xl leading-none text-[#fff4e8]">Order queue</h2><p className="mt-3 text-sm text-[#c9b097]">Customer contact details, order notes, and exact items are retained for every WhatsApp request.</p></div>{ordersQuery.isLoading ? <div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-[#e4b878]" /></div> : <div className="divide-y divide-white/10">{orders.length ? orders.map(order => <OrderRow key={order.id} order={order} pending={advance.isPending} onAdvance={status => advance.mutate({ orderId: order.id, status })} />) : <div className="grid min-h-56 place-items-center text-center"><div><Coffee className="mx-auto text-[#e4b878]" /><h3 className="mt-4 font-display text-4xl text-[#fff4e8]">No orders brewing yet.</h3></div></div>}</div>}</section><ProductMediaManager /></div>; }
function OrderRow({ order, pending, onAdvance }: { order: any; pending: boolean; onAdvance: (status: "confirmed" | "preparing" | "ready" | "out_for_delivery" | "completed") => void }) { const state = statusMeta[order.status as keyof typeof statusMeta]; return <article className="grid gap-5 p-6 lg:grid-cols-[.8fr_1fr_1.2fr_.65fr]"><div><p className="text-[.65rem] font-bold tracking-[.14em] text-[#e2ad68]">{order.orderNumber}</p><p className="mt-3 font-semibold text-[#fff4e8]">{order.customerName}</p><p className="mt-1 text-xs text-[#c8af96]">Phone: {order.phone}</p>{order.whatsapp && <p className="text-xs text-[#c8af96]">WhatsApp: {order.whatsapp}</p>}<p className="mt-4 font-display text-3xl text-[#e8b875]">{order.totalPkr === null ? "Total to confirm" : formatPkr(order.totalPkr)}</p></div><div><p className="font-semibold text-[#f8eee2]">{order.orderType === "pickup" ? "Pickup" : "Delivery"}</p>{order.orderType === "delivery" && <><p className="mt-2 text-xs text-[#c8af96]">{order.deliveryAddress}</p><p className="text-xs text-[#c8af96]">{order.area}</p><p className="mt-3 text-xs text-[#c8af96]">{order.deliveryInstructions}</p></>}<span className="mt-4 inline-flex rounded-full border border-[#e3b572]/30 bg-[#e3b572]/10 px-3 py-1 text-xs font-bold text-[#e9c180]">{state.label}</span></div><div className="rounded-xl border border-white/8 bg-black/15 p-4 text-xs leading-5 text-[#cbb29a]"><p className="font-semibold text-[#fff4e8]">Items</p>{order.items?.map((item: any) => <p key={item.id}>{item.quantity} × {item.productName} — {formatPkr(item.unitPricePkr * item.quantity)}</p>)}{order.notes && <p className="mt-3 border-t border-white/10 pt-3"><b>Notes:</b> {order.notes}</p>}</div><div>{state.next ? <Button disabled={pending} onClick={() => onAdvance(state.next)} className="h-10 w-full rounded-full bg-[#e3b572] text-xs font-bold uppercase tracking-[.1em] text-[#160d09] hover:bg-[#f3cf96]">{state.next === "confirmed" ? "Confirm order" : state.next === "preparing" ? "Start preparing" : state.next === "ready" ? "Mark ready" : state.next === "out_for_delivery" ? "Out for delivery" : "Complete"}</Button> : <p className="text-center text-xs font-bold uppercase tracking-[.1em] text-[#a6d0ae]">{state.label}</p>}</div></article>; }
function Metric({ label, value, dark, green }: { label: string; value: number; dark?: boolean; green?: boolean }) { return <div className={`rounded-[1.55rem] border p-6 ${dark ? "border-[#e3b572]/18 bg-[#532a1f]/55 text-[#fffaf0]" : green ? "border-[#65ba7b]/22 bg-[#254831]/45 text-[#effff2]" : "border-white/10 bg-white/[.045] text-[#fffaf0]"}`}><p className="text-[.62rem] font-bold uppercase tracking-[.16em] opacity-70">{label}</p><p className="mt-5 font-display text-5xl leading-none">{value}</p></div>; }
function Restricted({ title, detail, action, onClick }: { title: string; detail: string; action: string; onClick: () => void }) { return <div className="cafe-shell grid min-h-screen place-items-center px-5 text-center text-[#fff4e8]"><div className="glass-panel max-w-md rounded-[2rem] p-9"><AlertTriangle className="mx-auto text-[#e4b878]" /><h1 className="mt-7 font-display text-6xl leading-[.82]">{title}</h1><p className="mt-5 text-sm leading-7 text-[#c9b097]">{detail}</p><button onClick={onClick} className="cinematic-button mt-8 rounded-full bg-[#e3b572] px-6 py-3 text-xs font-bold uppercase text-[#160d09]">{action}</button></div></div>; }
